const {test} = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {PGlite} = require('@electric-sql/pglite');
test('automatic study ledger: live ranking, private history, idle cap, takeover, retries, midnight and RLS', async t => {
  const db = new PGlite();
  t.after(()=>db.close());
  const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222';
  const c='33333333-3333-4333-8333-333333333333',d='44444444-4444-4444-8444-444444444444';
  await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);
    create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
    create function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$;
    grant usage on schema auth to anon,authenticated;insert into auth.users values('${a}'),('${b}');`);
  for (const name of ['202610080001_study_sync.sql','202610080002_focus_reliability.sql']) await db.exec(fs.readFileSync(path.join(__dirname,'../supabase/migrations',name),'utf8'));
  const login=async id=>{await db.exec('reset role;set role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);};
  const admin=async fn=>{await db.exec('reset role');await fn();await login(a);};
  const rpc=async (name,args=[]) => (await db.query('select public.'+name+'('+args.map((_,i)=>'$'+(i+1)).join(',')+') data',args)).rows[0].data;
  await login(a);await rpc('study_set_profile',['Test A',true]);
  const old=await rpc('study_focus_start',['ktvxl',60]);
  await admin(()=>db.query("update public.focus_sessions set elapsed_seconds=3600 where id=$1",[old.id]));
  await rpc('study_focus_action',[old.id,'finish']);
  await admin(()=>db.exec(fs.readFileSync(path.join(__dirname,'../supabase/migrations/202610090001_automatic_study_time.sql'),'utf8')));
  const pulse=(client,age,seq,claim=false,stop=false,sub='ktvxl')=>rpc('study_activity_pulse',[client,sub,age,seq,claim,stop]);
  assert.equal((await rpc('study_leaderboard',['today','all'])).me.minutes,60,'legacy credit changed');
  await assert.rejects(()=>rpc('study_focus_start',['ktvxl',25]));
  let s=await pulse(c,0,1,true);assert(s.active&&s.owned);assert.equal(s.elapsed_seconds,0);
  assert.equal((await pulse(d,0,1)).owned,false,'heartbeat stole another device');
  await admin(()=>db.query("update public.study_activity_windows set cursor_at=clock_timestamp()-interval '61 seconds',active_until=clock_timestamp()+interval '839 seconds' where user_id=$1",[a]));
  assert.equal((await rpc('study_leaderboard',['today','ktvxl'])).me.minutes,61,'running minute not visible on board');
  s=await pulse(c,61,2);assert.equal(s.credited,true);
  let history=await rpc('study_snapshot');assert.equal(history.records['study|ktvxl|'+new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())].value,1);
  assert.equal((await pulse(c,61,2)).elapsed_seconds>=61,true);
  assert.equal((await rpc('study_leaderboard',['today','all'])).me.minutes,61,'retry doubled credit');
  await pulse(d,0,2,true);assert.equal((await pulse(c,0,3)).owned,false);
  assert.equal((await pulse(c,60,4,true)).owned,false,'queued older activity stole the new owner');
  await pulse(c,900,5,false,true);assert.equal((await pulse(d,1,3)).active,true,'old tab stop cancelled new owner');
  await pulse(d,900,4,false,true);
  assert.equal((await pulse(c,60,6,true)).active,false,'stale other tab reopened a stopped account window');
  assert.equal((await pulse(d,0,3,true)).active,false,'delayed start reopened stopped session');
  await pulse(d,0,5,true);
  await admin(()=>db.query("update public.study_activity_windows set cursor_at=clock_timestamp()-interval '930 seconds',active_until=clock_timestamp()-interval '30 seconds' where user_id=$1",[a]));
  s=await pulse(d,900,6,false,true);assert.equal(s.elapsed_seconds,900,'idle cap must be exactly 15 minutes');
  assert.equal((await rpc('study_leaderboard',['today','all'])).me.minutes,76);
  assert.equal((await rpc('study_leaderboard',['today','xstk'])).me.minutes,0,'subject filter ignored');
  await pulse(d,0,7,true,false,'vldc');
  await admin(()=>db.query("update public.study_activity_windows set cursor_at=((clock_timestamp() at time zone 'Asia/Ho_Chi_Minh')::date::timestamp at time zone 'Asia/Ho_Chi_Minh')-interval '60 seconds',active_until=((clock_timestamp() at time zone 'Asia/Ho_Chi_Minh')::date::timestamp at time zone 'Asia/Ho_Chi_Minh')+interval '60 seconds' where user_id=$1",[a]));
  await pulse(d,900,8,false,true,'vldc');
  assert.equal((await rpc('study_leaderboard',['today','vldc'])).me.minutes,1,'Vietnam midnight did not split credit');
  const rows=(await db.query("select day,seconds from public.study_activity_credit where subject='vldc' order by day")).rows;
  assert.equal(rows.length,2);assert.deepEqual(rows.map(r=>Number(r.seconds)),[60,60]);
  await assert.rejects(()=>pulse(d,-1,9));await assert.rejects(()=>pulse(d,901,9));await assert.rejects(()=>pulse(d,0,0,true));
  await assert.rejects(()=>db.query('update public.study_activity_credit set seconds=999999'));
  await assert.rejects(()=>db.query('select * from public.study_activity_windows'));
  await login(b);assert.equal((await db.query('select * from public.study_activity_credit')).rows.length,0);
  await rpc('study_snapshot');await assert.rejects(()=>pulse(c,0,1,true),'placeholder username accepted');
  await rpc('study_set_profile',['Test B',true]);
  await db.exec("select set_config('request.jwt.claims','{\"is_anonymous\":true}',false)");
  await assert.rejects(()=>pulse(c,0,1,true),'anonymous Supabase session accepted');
  await db.exec("select set_config('request.jwt.claims','{}',false)");
  await pulse(c,0,1,true);assert.equal((await rpc('study_leaderboard',['today','all'])).me.minutes,0);
  await db.exec('reset role;set role anon');await assert.rejects(()=>pulse(c,0,1,true));
  assert.equal((await rpc('study_leaderboard',['today','all'])).rows.length,1);
});
