const {PGlite}=require('@electric-sql/pglite');
const path=require('node:path');
const fs=require('node:fs'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
(async()=>{
 const db=new PGlite();const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222';
 await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to anon,authenticated;insert into auth.users values('${a}'),('${b}');`);
 await db.exec(fs.readFileSync(path.join(__dirname,'../supabase/migrations/202610080001_study_sync.sql'),'utf8'));
 const login=async id=>{await db.exec('reset role;set role authenticated;');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);};
 const rpc=async(name,args=[])=>{const ret=await db.query('select public.'+name+'('+args.map((_,i)=>'$'+(i+1)).join(',')+') data',args);return ret.rows[0].data;};
 const denied=async(fn)=>{await assert.rejects(fn);};
 await login(a);let snap=await rpc('study_snapshot');assert.deepEqual(snap.records,{});
 const note={kind:'note',subject:'ktvxl',id:'1',rid:'note|ktvxl|1',opId:randomUUID(),baseVersion:0,value:{text:'Ghi chú 32 bit',color:'yellow',subject:'ktvxl',questionId:'1',updatedAt:0}};
 let res=await rpc('study_sync',[JSON.stringify([note])]);assert.equal(res.accepted[0],note.opId);assert.equal(res.records[note.rid].version,1);
 res=await rpc('study_sync',[JSON.stringify([note])]);assert.equal(res.records[note.rid].version,1,'Retry wrote twice');
 await denied(()=>rpc('study_sync',[JSON.stringify([{...note,value:{...note.value,text:'changed'}}])]));
 const stale={...note,opId:randomUUID(),value:{...note.value,text:'Other device'}};
 res=await rpc('study_sync',[JSON.stringify([stale])]);assert.equal(res.conflicts.length,1);assert.equal(res.records[note.rid].value.text,note.value.text);
 await login(b);assert.equal((await db.query('select * from public.study_records')).rows.length,0,'Private data exposed');assert.deepEqual((await rpc('study_snapshot')).records,{});
 await denied(()=>db.query('insert into public.study_records(user_id,record_key,kind,subject,record_id) values($1,$2,$3,$4,$5)',[a,'note|ktvxl|2','note','ktvxl','2']));
 await login(a);const invalid={...note,opId:randomUUID(),rid:'note|ktvxl|__proto__',id:'__proto__'};await denied(()=>rpc('study_sync',[JSON.stringify([invalid])]));
 await denied(()=>rpc('study_sync',[JSON.stringify([{...note,opId:randomUUID(),value:{...note.value,text:'x'.repeat(2001)}}])]));
 const deleted={...note,opId:randomUUID(),baseVersion:1,value:null};res=await rpc('study_sync',[JSON.stringify([deleted])]);assert.equal(res.records[note.rid].value,null);assert.equal(res.records[note.rid].version,2);
 res=await rpc('study_sync',[JSON.stringify([stale])]);assert.equal(res.conflicts.length,1,'Tombstone did not block stale resurrection');
 const day=new Date(Date.now()+7*3600000).toISOString().slice(0,10),study={kind:'study',subject:'ktvxl',id:day,rid:'study|ktvxl|'+day,baseVersion:0,value:900,delta:900,opId:randomUUID()};
 await rpc('study_sync',[JSON.stringify([study])]);await rpc('study_sync',[JSON.stringify([study])]);assert.equal((await rpc('study_snapshot')).records[study.rid].value,900);
 assert.deepEqual((await rpc('study_leaderboard',['today','all'])).rows,[],'Manual minutes entered board');
 const session=await rpc('study_focus_start',['ktvxl',1]);await denied(()=>rpc('study_focus_start',['xstk',1]));await denied(()=>rpc('study_focus_action',[session.id,'finish']));
 await denied(()=>db.query("update public.focus_sessions set elapsed_seconds=60000 where id=$1",[session.id]));
 await rpc('study_focus_action',[session.id,'pause']);await rpc('study_focus_action',[session.id,'resume']);
 await login(b);await denied(()=>rpc('study_focus_action',[session.id,'cancel']));await login(a);
 await db.exec('reset role');await db.query('update public.focus_sessions set elapsed_seconds=60 where id=$1',[session.id]);await login(a);
 const done=await rpc('study_focus_action',[session.id,'finish']);assert.equal(done.credited_minutes,1);await rpc('study_focus_action',[session.id,'finish']);
 assert.deepEqual((await rpc('study_leaderboard',['today','all'])).rows,[],'Opt-out ignored');
 await rpc('study_set_profile',['Người học A',true]);let board=await rpc('study_leaderboard',['today','all']);assert.equal(board.rows.length,1);assert.equal(board.rows[0].minutes,1);assert.equal(board.me.sessions,1);assert.equal(board.me.rank,1);
 assert.deepEqual((await rpc('study_leaderboard',['today','xstk'])).rows,[]);
 await db.exec("reset role;set role anon;select set_config('request.jwt.claim.sub','',false);");assert.equal((await rpc('study_leaderboard',['week','all'])).rows.length,1);await denied(()=>rpc('study_snapshot'));await denied(()=>db.query('select * from public.study_profiles'));
 await login(a);await rpc('study_set_profile',['Người học A',false]);assert.deepEqual((await rpc('study_leaderboard',['today','all'])).rows,[]);
 console.log('PASS: PostgreSQL migration, RLS account isolation, anonymous restrictions, validated sync, note conflicts/tombstones, idempotency, server timer, leaderboard opt-in and subject filters.');await db.close();
})().catch(e=>{console.error(e.message);process.exitCode=1;});
