const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {PGlite}=require('@electric-sql/pglite'),{randomUUID}=require('node:crypto');
test('server history ignores forged minute edits and restores snapshots without blocking answers or notes',async t=>{
  const db=new PGlite();t.after(()=>db.close());
  const uid=randomUUID(),client=randomUUID();
  await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);
    create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
    create function auth.jwt() returns jsonb language sql stable as $$select '{}'::jsonb$$;
    grant usage on schema auth to anon,authenticated;`);
  await db.query('insert into auth.users values($1)',[uid]);
  const migrate=async name=>db.exec(fs.readFileSync(path.join(__dirname,'../supabase/migrations',name),'utf8'));
  for(const file of ['202610080001_study_sync.sql','202610080002_focus_reliability.sql','202610090001_automatic_study_time.sql','202610100001_study_garden.sql'])await migrate(file);
  const login=async()=>{await db.exec('reset role;set role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[uid]);};
  const rpc=async(name,args=[]) => (await db.query('select public.'+name+'('+args.map((_,i)=>'$'+(i+1)).join(',')+') data',args.map(x=>x&&typeof x==='object'?JSON.stringify(x):x))).rows[0].data;
  await login();await rpc('study_set_profile',['Học viên',true]);
  const day=new Date(Date.now()+7*3600000).toISOString().slice(0,10),rid='study|ktvxl|'+day;
  const old={kind:'study',subject:'ktvxl',id:day,rid,baseVersion:0,value:31,delta:31,opId:randomUUID()};
  await rpc('study_sync',[[old]]);
  await db.exec('reset role');await migrate('202610100002_readonly_study_history.sql');await login();
  assert.equal((await rpc('study_snapshot')).records[rid].value,31,'existing history changed');
  const forged={...old,value:100031,delta:100000,opId:randomUUID()};
  const note={kind:'note',subject:'ktvxl',id:'1',rid:'note|ktvxl|1',baseVersion:0,value:{text:'32 bit',color:'yellow'},opId:randomUUID()};
  let result=await rpc('study_sync',[[forged,note]]);
  assert.deepEqual(result.ignored,[forged.opId]);assert.ok(result.accepted.includes(note.opId));
  assert.equal(result.records[rid].value,31);assert.equal(result.records[note.rid].value.text,'32 bit');
  result=await rpc('study_sync',[[{...forged,opId:randomUUID(),value:null,delta:-31}]]);
  assert.equal(result.records[rid].value,31,'client deleted history');
  assert.equal(result.records[rid].version,1,'discarded edits changed version');
  await assert.rejects(()=>rpc('study_sync_before_readonly_history',[[forged]]));
  await assert.rejects(()=>db.query("update public.study_records set value='100000' where record_key=$1",[rid]));
  const garden=await rpc('study_garden_snapshot');assert.equal(garden.state.totalSeconds,0);
  await rpc('study_activity_pulse',[client,'ktvxl',0,1,true,false]);
  await db.exec('reset role');await db.query("update public.study_activity_windows set cursor_at=clock_timestamp()-interval '120 seconds',active_until=clock_timestamp()+interval '15 minutes' where user_id=$1",[uid]);await login();
  await rpc('study_activity_pulse',[client,'ktvxl',0,2,false,false]);
  assert.equal((await rpc('study_snapshot')).records[rid].value,33,'server credit blocked');
  assert.equal((await rpc('study_leaderboard',['today','all'])).me.minutes,2,'forged history entered board');
  assert.equal((await rpc('study_garden_snapshot')).state.totalSeconds,120,'fake minutes grew garden');
  result=await rpc('study_sync',[[forged]]);assert.equal(result.records[rid].value,33,'retry forged credit');
  await db.exec('reset role;set role anon');await db.query("select set_config('request.jwt.claim.sub','',false)");
  await assert.rejects(()=>rpc('study_sync',[[forged]]));
});
