/* Feature announcements only. Preserve stable IDs so read status stays intact. */
window.KMA_SITE_UPDATES = [
  { id: '2026-10-10-account-study-garden', date: '10/10/2026', title: 'Vườn học tập & bộ sưu tập',
    added: ['Học cả 4 môn để nhận hạt mỗi 25 phút; học liên tục đủ 60/120 phút nhận thêm hạt hiếm/sử thi.', 'Gieo cây, thu hoạch vật phẩm và sắp xếp hộp trưng bày trong hồ sơ của bạn.', 'Bấm tên trên bảng xếp hạng để xem bộ sưu tập, hộp trưng bày và tổng giá trị vật phẩm của nhau.'] },
  { id: '2026-10-09-automatic-study-time', date: '09/10/2026', title: 'Tự động tính thời gian học',
    added: ['Thời gian tự tính khi bạn làm bài hoặc đọc kiến thức, giúp tích lũy chuỗi học và lên bảng xếp hạng.', 'Sau 15 phút không thao tác, đồng hồ chuyển sang Nghỉ ngơi; học tiếp để bắt đầu lượt mới.', 'Xem thời gian đã học theo từng môn và từng ngày trong tab Đã học.'] },
  { id: '2026-10-09-learning-account-name', date: '09/10/2026', title: 'Chọn biệt danh khi đăng nhập',
    added: ['Đăng nhập Google để chọn đáp án và lưu tiến trình ôn tập theo tài khoản.', 'Chọn biệt danh riêng để mọi người nhận ra bạn trên bảng xếp hạng.'] },
  { id: '2026-10-09-responsive-study-tools', date: '09/10/2026', title: 'Thanh công cụ học tập',
    added: ['Máy tính: mở Giờ học, Xếp hạng và Ghi chú từ thanh dọc; bấm tay cầm = để thu/mở, kéo để đổi vị trí.', 'Điện thoại: chạm tay cầm hoặc vuốt khay công cụ từ đáy màn hình để mở.'] },
  { id: '2026-10-09-paper-highlights', date: '09/10/2026', title: 'Highlight với 6 màu giấy nhớ',
    added: ['Bôi đen chữ rồi bấm cây cọ để tô màu đề bài, đáp án, lời giải và Kiến thức trọng tâm ở cả bốn môn.', 'Chọn màu Cần nhớ, Hay nhầm, Khó, Đã hiểu, Cần hỏi hoặc Mẹo hay; bấm đoạn đã tô để đổi màu hoặc xóa.', 'Các đoạn tô màu được lưu trên trình duyệt bạn đang dùng.'] },
  { id: '2026-10-08-streak-focus-reliability', date: '08/10/2026', title: 'Chuỗi học & bản đồ thời gian',
    added: ['Chuỗi học có 5 cấp ở mốc 1, 2, 3, 5 và 7 ngày liên tiếp; bấm ngọn lửa trên thanh trạng thái để xem.', 'Bản đồ trong tháng có màu riêng từng môn và đánh dấu ngày thi; bấm ngày để xem thời gian học từng môn.'] },
  { id: '2026-10-08-google-sync-leaderboard', date: '08/10/2026', title: 'Đăng nhập Google & bảng xếp hạng',
    added: ['Dùng cùng tài khoản Google để tiếp tục ôn tập trên máy tính và điện thoại, với câu đã làm, dấu sao, ghi chú và lịch sử học.', 'Xem bảng xếp hạng thời gian học theo ngày, tuần, tháng hoặc môn học.'] },
  { id: '2026-10-08-notes-updates', date: '08/10/2026', title: 'Ghi chú riêng cho từng câu',
    added: ['Ghi chú dưới câu hỏi với 6 màu giấy nhớ ở giao diện sáng/tối; bấm thẻ hoặc nút bút để sửa.', 'Lưu, xóa, hoàn tác và mở rộng ghi chú dài trên máy tính hoặc điện thoại.', 'Bấm chuông Cập nhật để khám phá tính năng mới và đánh dấu thông báo đã đọc.'] },
  { id: '2026-10-08-inline-answers', date: '08/10/2026', title: 'Lời giải ngay dưới câu hỏi',
    added: ['Đọc lời giải trực tiếp dưới câu hỏi sau khi chọn đáp án.', 'Thư giãn giữa giờ với xúc xắc 3D và lời chúc ôn thi.'] },
  { id: '2026-10-07-halloween-music', date: '07/10/2026', title: 'Góc học đêm & nhạc chill',
    added: ['Giao diện tối mang không khí Halloween với trăng, bí ngô và ngôi nhà học đêm.', 'Thêm nhạc vào danh sách cá nhân, tìm kiếm, chuyển bài, lặp và quản lý danh sách trong tab Nhạc chill.'] },
  { id: '2026-10-07-diagrams-exams', date: '07/10/2026', title: 'Sơ đồ kiến thức & thi thử',
    added: ['Khám phá sơ đồ kiến thức của cả bốn môn; chọn từng thành phần để xem nội dung liên quan.', 'Mở sơ đồ toàn màn hình và luyện thi với đề thi thử.'] }
];
